/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-01-09 09:31:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.region;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recommand_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635998956472L));
    _jspx_dependants.put("jar:file:/Users/nz/DEV/koravelProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/koravelProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\t\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../resources/css/detail.css\">\n");
      out.write("\t\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resources/css/festival_style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resources/css/festival_isotope.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\n");
      out.write("\t\n");
      out.write("\t<!-- JavaScript Libraries -->\n");
      out.write("    <script src=\"../resources/js/jquery.min.js\"></script>\n");
      out.write("        \n");
      out.write("    <script src=\"../resources/js/festival_jquery.isotope.min.js\"></script>\n");
      out.write("    <script src=\"../resources/js/js_regionrecommand.js\"></script>\n");
      out.write("    <script src=\"../resources/js/js_recommand_pagenation.js\"></script>\n");
      out.write("    \n");
      out.write("<title>여행지 정보</title>\n");
      out.write("<body>\n");
      out.write("\t<nav class=\"navbar\">\n");
      out.write("    <div class=\"navbar_logo\">          \n");
      out.write("      <a href=\"../index.jsp\">koravel</a>\n");
      out.write("    </div>\n");
      out.write("    <ul class=\"navbar_menu\">\n");
      out.write("      <li><a href=\"../region/recommand.do\">여행지 정보</a></li>\n");
      out.write("      <li><a href=\"../region/festival.do\">지역행사</a></li>\n");
      out.write("      <li><a href=\"../board/getBoardMain.do\">커뮤니티</a></li>\n");
      out.write("      <li><a href=\"../main/tip.do\">팁</a></li>\n");
      out.write("      <li><a href=\"\">북마크</a></li>\n");
      out.write("    </ul>        \n");
      out.write("\t</nav>\n");
      out.write("\t<!-- 헤더 -->\n");
      out.write("\t\n");
      out.write("\t<section class=\"container\">\n");
      out.write("        <article class=\"column col5\">\n");
      out.write("            <h3><em class=\"col_tit\">여행지 정보</em></h3>\n");
      out.write("            <p class=\"col_desc\">다양한 여행지를 찾아보세요!</p>\n");
      out.write("        <!-- contents -->\n");
      out.write("        <div id=\"customizing\">\n");
      out.write("            <div class=\"container\">                \n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div id=\"options\" class=\"gridly\">\n");
      out.write("                        <ul class=\"filter option-set\" data-filter-group=\"color\">\n");
      out.write("                            <li><a href=\"#filter-color-any\" data-filter-value=\"\" class=\"selected\">전체</a></li>\n");
      out.write("                            <li class=\"webstandard\"><a href=\"recommand.do?regionSumAddr='서울'\" data-filter-value=\".one\">서울</a></li>\n");
      out.write("                            <li class=\"webstandard\"><a href=\"#filter-color-webstandard\" data-filter-value=\".two\">경기도</a></li>\n");
      out.write("                            <li class=\"webstandard\"><a href=\"#filter-color-webstandard\" data-filter-value=\".thr\">강원도</a></li>\n");
      out.write("                            <li class=\"webstandard\"><a href=\"#filter-color-webstandard\" data-filter-value=\".fou\">전라도</a></li>\n");
      out.write("                            <li class=\"webstandard\"><a href=\"#filter-color-webstandard\" data-filter-value=\".fiv\">경상도</a></li>\n");
      out.write("                            <li class=\"webstandard\"><a href=\"#filter-color-webstandard\" data-filter-value=\".six\">충청도</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>    \n");
      out.write("                <div class=\"row\" id=\"middle\" style=\"margin-left:16px;\">\n");
      out.write("                    <div id=\"container\" class=\"clearfix\">    \n");
      out.write("                        <!-- box -->                       \n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <!-- //container-->\n");
      out.write("                </div>\n");
      out.write("                <!-- //row -->\n");
      out.write("            </div>\n");
      out.write("            <!-- //container-->\n");
      out.write("        </div>\n");
      out.write("        <!-- //contents -->\n");
      out.write("        </article>\n");
      out.write("        </section>\n");
      out.write("        \n");
      out.write("        <nav aria-label=\"Page navigation example\">\t\t\n");
      out.write("\t\t  <ul id=\"dyn_ul\" class=\"pagination\" style=\"justify-content: center;\">\n");
      out.write("\t\t    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">이전</a></li>\n");
      out.write("\t\t    <li class=\"page-item parent_li\" id=\"parent_li\"><a class=\"page-link\" id=\"currentPage\" href=\"#\">1</a></li>\t    \n");
      out.write("\t\t    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">다음</a></li>\n");
      out.write("\t\t  </ul>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("   \n");
      out.write("    \n");
      out.write("   ");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<footer>\n");
      out.write("\t\t<div class=\"footer1\">\n");
      out.write("\t\t\t<div class=\"navbar_logo\">\n");
      out.write("\t\t\t\t<i class=\"fab fa-accusoft\"></i>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\tKoravel <br> Addr. 서울특별시 금천구 가산디지털1로 151 2F<br> Tel.\n");
      out.write("\t\t\t\t02 - 123 - 4567<br> COPYRIGHT 2021. Koravel. ALL RIGHT\n");
      out.write("\t\t\t\tRESERVED.\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\n");
      out.write("\t<script>       \n");
      out.write("        // 박스\n");
      out.write("        $(function() {\n");
      out.write("            var $container = $('#container'),\n");
      out.write("                filters = {};\n");
      out.write("\n");
      out.write("            $container.isotope({\n");
      out.write("                itemSelector: '.color-shape',\n");
      out.write("                masonry: {\n");
      out.write("                    columnWidth: 57\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            // filter buttons\n");
      out.write("            $('.filter a').click(function() {\n");
      out.write("                var $this = $(this);\n");
      out.write("                // don't proceed if already selected\n");
      out.write("                if ($this.hasClass('selected')) {\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                var $optionSet = $this.parents('.option-set');\n");
      out.write("                // change selected class\n");
      out.write("                $optionSet.find('.selected').removeClass('selected');\n");
      out.write("                $this.addClass('selected');\n");
      out.write("                // store filter value in object\n");
      out.write("                // i.e. filters.color = 'red'\n");
      out.write("                var group = $optionSet.attr('data-filter-group');\n");
      out.write("                filters[group] = $this.attr('data-filter-value');\n");
      out.write("                // convert object into array\n");
      out.write("                var isoFilters = [];\n");
      out.write("                for (var prop in filters) {\n");
      out.write("                    isoFilters.push(filters[prop])\n");
      out.write("                }\n");
      out.write("                var selector = isoFilters.join('');\n");
      out.write("                $container.isotope({\n");
      out.write("                    filter: selector\n");
      out.write("                });\n");
      out.write("                return false;\n");
      out.write("            });\n");
      out.write("            $('.tit_btn').on('click', function(e) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                $('.nav_container').toggleClass('on');\n");
      out.write("            });\n");
      out.write("            $(\".click\").click(function() {\n");
      out.write("                $(\".view\").fadeToggle();\n");
      out.write("            });\n");
      out.write("        });        \n");
      out.write("    </script>            \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/region/recommand.jsp(62,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("region");
      // /WEB-INF/views/region/recommand.jsp(62,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/region/recommand.jsp(62,6) '${regionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${regionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/region/recommand.jsp(62,6) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t<section class=\"color-shape one\">\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"detailRegion.do?regionIdx=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("                                <div class=\"image-wrap\">\n");
            out.write("                                    <div class=\"hover-wrap\">\n");
            out.write("                                        <span class=\"overlay-img-donut\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("                                        <span class=\"overlay-text-thumb-donut\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionSumAddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("                                        <span class=\"overlay-text-thumb1-donut\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionStar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("                                        <span class=\"overlay-text-thumb2-donut\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("                                    </div>\n");
            out.write("                                    <img src=\"../resources/images/region/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionMainImgFile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"portfolio\">\n");
            out.write("                                    <div class=\"img-text donutImg\">\n");
            out.write("                                        <h5>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\n");
            out.write("                                        <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionSumAddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("                                        <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionStar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("                                        <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("                                    </div>\n");
            out.write("                                </div>\n");
            out.write("                            \t</a>\n");
            out.write("\t\t\t\t\t\t\t\t</section>\n");
            out.write("                        <!-- //box -->\n");
            out.write("                        \n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/region/recommand.jsp(63,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loop.last }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<input id=\"endIdx\" type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region.regionIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
