/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-01-12 07:53:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635998956472L));
    _jspx_dependants.put("jar:file:/Users/nz/DEV/koravelProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/koravelProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <!-- Required meta tags -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\" integrity=\"sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("\t<!-- Kakao API APP KEY -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=46b23103bbef6793e908db1d8cca7e25\"></script>\n");
      out.write("\t\n");
      out.write("\t<!-- JqueryCSS -->\n");
      out.write("\t<link href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\n");
      out.write("\t<!-- PopUP / AJAX -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.5.1.min.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\" ></script>\n");
      out.write("\n");
      out.write("\t<!-- CSS -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../resources/css/boardStyle.css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t//alert(\"게시글 쓰기 준비 안료\")\n");
      out.write("\t$('#courseBoard').hide();\n");
      out.write("\t$('#regionBoard').hide();\n");
      out.write("\n");
      out.write("\t$('#boardCat').change(function() {\n");
      out.write("\t\tvar state = $('#boardCat option:selected').val();\n");
      out.write("\t\tif (state == 'course') {\n");
      out.write("\t\t\t$('#freeBoard').hide();\n");
      out.write("\t\t\t$('#courseBoard').show();\n");
      out.write("\t\t\t$('#regionBoard').hide();\n");
      out.write("\t\t}\n");
      out.write("\t\telse if (state == 'region') {\n");
      out.write("\t\t\t$('#freeBoard').hide();\n");
      out.write("\t\t\t$('#courseBoard').hide();\n");
      out.write("\t\t\t$('#regionBoard').show();\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\t$('#freeBoard').show();\n");
      out.write("\t\t\t$('#courseBoard').hide();\n");
      out.write("\t\t\t$('#regionBoard').hide();\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$('input#boardTitle').val(\"\");\n");
      out.write("\t\n");
      out.write("\t$('#boardType').change(function() {\n");
      out.write("\t\t\n");
      out.write("\t\tvar type = $('#boardType option:selected').val();\n");
      out.write("\t\tif (type == 'family') {\n");
      out.write("\t\t\t$('input#boardTitle').val(\"[가족과 함께]\");\n");
      out.write("\t\t}\n");
      out.write("\t\telse if (type == 'child') {\n");
      out.write("\t\t\t$('input#boardTitle').val(\"[자녀와 함께]\");\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\t$('input#boardTitle').val(\"[커플 추천]\");\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}) // .ready(function end\n");
      out.write("\t\t\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("function keywordPopup(){\n");
      out.write("\t\twindow.name = \"insertBoardForm\";\n");
      out.write("\t\tvar url = \"keywordPop.do\";\n");
      out.write("\t    var name = \"keywordPop\";\n");
      out.write("\t    var option = \"width = 500, height = 500, top = 100, left = 200, location = no\";\n");
      out.write("\t    window.open(url, name, option);\n");
      out.write("\t}; // keywordPopup end\n");
      out.write("\t\n");
      out.write("function setChildValue(sendWord){\n");
      out.write("\tdocument.getElementById(\"#boardKeyword\").value = sendWord;\n");
      out.write("} // setChildValue(sendWord) end 키워드 팝업창에서 작성 완료한 키워드 텍스트 가지고 오기\n");
      out.write("\t\n");
      out.write("function setThumbnail(event) {\n");
      out.write("\t$(\"#image_container\").empty();\n");
      out.write("\tvar reader = new FileReader();\n");
      out.write("\treader.onload = function(event) {\n");
      out.write("\t\tvar img = document.createElement(\"img\");\n");
      out.write("\t\timg.setAttribute(\"src\", event.target.result);\n");
      out.write("\t\tdocument.querySelector(\"div#image_container\").appendChild(img);\n");
      out.write("\t};\n");
      out.write("\treader.readAsDataURL(event.target.files[0]);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/** 아이템을 등록한다. */\n");
      out.write("function submitItem() {\n");
      out.write("\tvar boardContent2 = [];\n");
      out.write("\t\n");
      out.write("    if(!validateItem()) {\n");
      out.write("    \treturn;\n");
      out.write("    }\n");
      out.write("    else{\n");
      out.write("    \t$(\".itemBox .regionSearch\").each(function(index, element){\n");
      out.write("    \t\tboardContent2.push($(this).val());\n");
      out.write("    \t});\n");
      out.write("    \t$(\"#boardContent2\").val(boardContent2.toString());\n");
      out.write("    \talert(\"현재 코스로 적용 되었습니다.\");\n");
      out.write("    \talert(boardContent2.toString());\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("/** 아이템 체크 */\n");
      out.write("function validateItem() {\n");
      out.write("    var items = $(\"input[type='text'][name='regionSearch']\");\n");
      out.write("    if(items.length == 0) {\n");
      out.write("        alert(\"작성된 아이템이 없습니다.\");\n");
      out.write("        return false;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    var flag = true;\n");
      out.write("    for(var i = 0; i < items.length; i++) {\n");
      out.write("        if($(items.get(i)).val().trim() == \"\") {\n");
      out.write("            flag = false;\n");
      out.write("            alert(\"내용을 입력하지 않은 항목이 있습니다.\");\n");
      out.write("            break;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    return flag;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/** UI 설정 */\n");
      out.write("$(function() {\n");
      out.write("    $(\"#itemBoxWrap\").sortable({\n");
      out.write("        placeholder:\"itemBoxHighlight\",\n");
      out.write("        start: function(event, ui) {\n");
      out.write("            $(this).attr('start_pos', ui.item.index()); // 기존 순서값을 data-previndex에 저장 \n");
      out.write("        },\n");
      out.write("        stop: function(event, ui) {\n");
      out.write("            var spos = Number(ui.item.index())+1; // index값이 0에서 시작하기 때문에 1 더하기 \n");
      out.write("            var epos = Number($(this).attr('data-previndex')) + 1;\n");
      out.write("            var grpno = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.grpno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // item group key\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    $( \"#sortable\" ).sortable();\n");
      out.write("    $( \"#sortable\" ).disableSelection();\n");
      out.write("});\n");
      out.write("\n");
      out.write("/** 아이템 순서 조정 */\n");
      out.write("function reorder() {\n");
      out.write("    $(\".itemBox\").each(function(i, box) {\n");
      out.write("        $(box).find(\".itemNum\").html(i + 1);\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("/** 아이템 추가 */\n");
      out.write("function createItem() {\n");
      out.write("    $(createBox())\n");
      out.write("    .appendTo(\"#itemBoxWrap\")\n");
      out.write("    .hover(\n");
      out.write("        function() {\n");
      out.write("            $(this).css('backgroundColor', '#f9f9f5');\n");
      out.write("            $(this).find('.deleteBox').show();\n");
      out.write("        },\n");
      out.write("        function() {\n");
      out.write("            $(this).css('background', 'none');\n");
      out.write("            $(this).find('.deleteBox').hide();\n");
      out.write("        }\n");
      out.write("    )\n");
      out.write("\t\t.append(\"<div class='deleteBox'>[삭제]</div>\")\n");
      out.write("\t\t.find(\".deleteBox\").click(function() {\n");
      out.write("        var valueCheck = false;\n");
      out.write("        $(this).parent().find('input').each(function() {\n");
      out.write("            if($(this).attr(\"name\") != \"type\" && $(this).val() != '') {\n");
      out.write("                valueCheck = true;\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        if(valueCheck) {\n");
      out.write("            var delCheck = confirm('입력하신 내용이 있습니다.\\n삭제하시겠습니까?');\n");
      out.write("        }\n");
      out.write("        if(!valueCheck || delCheck == true) {\n");
      out.write("            $(this).parent().remove();\n");
      out.write("            reorder();\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    reorder(); // 숫자를 다시 붙인다.\n");
      out.write("}\n");
      out.write("\n");
      out.write("/** 아이템 박스 작성 */\n");
      out.write("function createBox() {\n");
      out.write("    var contents = \"<div class='itemBox'>\"\n");
      out.write("                 + \"<div class='row' style='float:center;'>\"\n");
      out.write("                 + \"<div class='col-1'></div><span class='itemNum'></span>\"\n");
      out.write("                 + \"<input type='text' class='col-9 regionSearch' name='item'>\"\n");
      out.write("                 + \"</div>\"\n");
      out.write("                 + \"</div>\";\n");
      out.write("    return contents;\n");
      out.write("}\n");
      out.write("//]]>\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\t\n");
      out.write("<style>\n");
      out.write("\t#sortable { list-style-type: none; margin: 0; padding: 0; width: 400px; }\n");
      out.write("\t#sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }\n");
      out.write("\t#sortable li span { position: absolute; margin-left: -1.3em; }\n");
      out.write("</style>\n");
      out.write("\t\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t<!-- header -->\n");
      out.write("\t\n");
      out.write("\t<header style=\"min-width:1280px; height:200px; margin:auto; background-color: black; \">\n");
      out.write("\t\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- 글 작성 메인 페이지 영역 시작 -->\n");
      out.write("\t\n");
      out.write("\t<main>\n");
      out.write("\t\n");
      out.write("\t<div>\n");
      out.write("\n");
      out.write("\t\t<form action=\"saveBoard.do\" method='post' enctype=\"multipart/form-data\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t");

		session.getAttribute("usrNick");
	
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\" style=\"background-color: white;\">\n");
      out.write("\t\t\t\t<div class=\"col-1\"></div>\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"boardWriter\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usrNick.usrID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t\t\t\t<mark class=\"col-1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usrNick.usrID }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</mark>\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"col-7\" name=\"boardTitle\" id=\"boardTitle\" placeholder=\"제목을 작성해 주세요.\" value=\"\">\n");
      out.write("\t\t\t\t<select class=\"col-2\" name=\"boardType\" id=\"boardType\">\n");
      out.write("\t\t\t\t\t<option value=\"family\" selected>가족과 함께</option>\n");
      out.write("\t\t\t\t\t<option value=\"child\">자녀와 함께</option>\n");
      out.write("\t\t\t\t\t<option value=\"couple\">커플 추천</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-1\"></div>\n");
      out.write("\t\t\t\t<!-- 키워드 선택 팝업 -->\n");
      out.write("\t\t\t\t<a class=\"col-1\" href=\"javascript:;\" onclick=\"keywordPopup()\" ><img src=\"../resources/images/Board/key.PNG\" style=\"height:30px;\"/></a>\n");
      out.write("\t\t\t\t<!-- 키워드 팝업 결과값 노출 -->\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"col-7\" disabled name=\"boardKeyword\" id=\"boardKeyword\" value=\"선택된 키워드가 없습니다.\">\n");
      out.write("\t\t\t\t<select class=\"col-2\" name=\"boardCat\" id=\"boardCat\">\n");
      out.write("\t\t\t\t\t<option value=\"free\" selected>자유게시판</option>\n");
      out.write("\t\t\t\t\t<option value=\"course\">나만의 코스 공유</option>\n");
      out.write("\t\t\t\t\t<option value=\"region\">여행 정보 공유</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t\t<div class=\"col-1\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 자유게시판 -->\n");
      out.write("\t\t\t<div class=\"row\" id=\"freeBoard\">\n");
      out.write("\t\t\t\t<div class=\"col-1\"></div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-10\">\n");
      out.write("\t\t\t\t\t<textarea class=\"w-100 h-100 contentBox\" name=\"boardContent1\" id=\"boardContent1\" placeholder=\"자유롭게 글을 남겨 주세요\"></textarea>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-1\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 코스 게시판 -->\n");
      out.write("\t\t\t<div class=\"row\" id=\"courseBoard\">\n");
      out.write("\t\t\t\t<div class=\"col-1\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-6\">\n");
      out.write("\t\t\t\t\t<textarea class=\"w-100 p-12 h-100 contentBox\" name=\"boardContent1\" id=\"boardContent1\" placeholder=\"선택하신 코스에 대해 얘기 해주세요.\"></textarea>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-4\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t    <div class=\"col-5\" style=\"float:left;\">아이템 추가 : </div>\n");
      out.write("\t\t\t\t\t    <div class=\"col-7\" style=\"clar:both;\">\n");
      out.write("\t\t\t\t\t        <input type=\"button\" class=\"button\" id=\"addItem\" value=\"추가\" onclick=\"createItem();\" />\n");
      out.write("\t\t\t\t\t        <input type=\"button\" class=\"button\" id=\"applyItem\" value=\"적용\" onclick=\"submitItem();\" />\n");
      out.write("\t\t\t\t\t    </div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"row\"><input class=\"col-10\" type=\"text\" disabled name=\"boardContent2\" id=\"boardContent2\" placeholder=\"코스를 설정해주세요\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"row\"><br/></div>\n");
      out.write("\t\t\t\t\t<div id=\"itemBoxWrap\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-1\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 관광지 게시판 -->\n");
      out.write("\t\t\t<div class=\"row\" id=\"regionBoard\">\n");
      out.write("\t\t\t\t<div class=\"col-1\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-6\" >\n");
      out.write("\t\t\t\t\t<textarea class=\"w-100 p-12 h-100 contentBox\" name=\"boardContent1\" id=\"boardContent1\" placeholder=\"관광지에 대해 설명해 주세요\"></textarea>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-4\">\n");
      out.write("\t\t\t\t\t<div style=\"margin:auto\" id=\"usrFotoZone\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"col-12\" name=\"boardRegion\" id=\"boardRegionSelect\" placeholder=\"선택된 관광지가 없습니다.\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"row\"><br/></div>\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" class=\"w-100 p-12 h-100\" maxlength=\"60\" size=\"40\" name=\"file\" id=\"image\" onchange=\"setThumbnail(event);\"/>\n");
      out.write("\t\t\t\t\t\t<div id=\"image_container\" style=\"height:350px\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-1\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-1\">\n");
      out.write("\t\t\t\t\t<br/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-2\">\n");
      out.write("\t\t\t\t\t<button class=\"button\" onclick='location.href=\"getBoardList.do\"'>글 목록</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-1\">\n");
      out.write("\t\t\t\t\t<br/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-5\">\n");
      out.write("\t\t\t\t\t<br/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<input class=\"col-2 button\" type=\"submit\" value=\"새글 등록\"/>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"col-1\">\n");
      out.write("\t\t\t\t\t<br/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<br/>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t</main>\n");
      out.write("\t\n");
      out.write("\t<!-- 글 작성 메인 페이지 영역 끝 -->\n");
      out.write("\t\n");
      out.write("\t<!-- footer -->\n");
      out.write("\t\n");
      out.write("\t<footer>\n");
      out.write("\t\t<div class=\"footer_wrap\">\n");
      out.write("\t\t\t<img src=\"../resources/images/koravel.png\"><br><br>\n");
      out.write("\t\t\t  상호명 : Koravel<br>\n");
      out.write("\t\t\t  주소 : 서울시 금천구 가산동 426-5 월드메르디앙 2차 413호<br>\n");
      out.write("\t\t\tTEL : 02-AAA-BBBB<br>\n");
      out.write("\t\t\tCopyright© 2021 Koravel, All Right Reserved.<br>\n");
      out.write("\t\t\t<ul class=\"footer_ul\">\n");
      out.write("\t\t\t    <li id =\"introduce\">Koravel 소개 </li><p>|</p>\n");
      out.write("\t\t\t    <li id=\"agreements\">이용 약관 </li><p>|</p>\n");
      out.write("\t\t\t    <li id=\"policy\">개인정보 처리방침</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Optional JavaScript; choose one of the two! -->\n");
      out.write("\n");
      out.write("    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.5.1.min.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("    <!-- Option 2: Separate Popper and Bootstrap JS -->\n");
      out.write("    <!--\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js\" integrity=\"sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2\" crossorigin=\"anonymous\"></script>\n");
      out.write("    -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
