/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-01-07 10:00:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635998956472L));
    _jspx_dependants.put("jar:file:/Users/nz/DEV/koravelProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/koravelProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" content=\"no-cache\">\n");
      out.write("<title>국내 최강 여행 전문 플랫폼, KORAVEL</title>\n");
      out.write("<link href=\"../resources/css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- slick slider  -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"../resources/js/main.js\" defer></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"../resources/js/ex.js\" defer></script>\n");
      out.write("<style>\n");
      out.write("\t*{\n");
      out.write("\t\tfont-family: 'Jua', sans-serif;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function() {\n");
      out.write("    get_rate();\n");
      out.write(" \n");
      out.write("})\n");
      out.write("\n");
      out.write("function get_rate() {\n");
      out.write("    $.ajax({\n");
      out.write("        type: \"GET\",\n");
      out.write("        url : \"../currency.jsp\",\n");
      out.write("        data : {},\n");
      out.write("        contentType: \"application/x-www-form-urlencoded; charset=UTF-8\",\n");
      out.write("        success: function(response) {\t      \n");
      out.write("       \teval(response) // 스트링을 코드로 만들어줘서 객체로 활용\n");
      out.write("       \tlet ranNum = Math.floor(Math.random() * 10) +1;\n");
      out.write("\t\tlet rate = exView.리스트[ranNum].통화명\n");
      out.write("        let now_rate = exView.리스트[ranNum].매매기준율;\n");
      out.write("      $('#rate').text(rate);\n");
      out.write("      $('#now-rate').text(now_rate);\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("}\n");
      out.write("(function(){\n");
      out.write("\tvar w = window;\n");
      out.write("\tif (w.ChannelIO) {\n");
      out.write("\t  return (window.console.error || window.console.log || function(){})('ChannelIO script included twice.');\n");
      out.write("\t}\n");
      out.write("\tvar ch = function() {\n");
      out.write("\t  ch.c(arguments);\n");
      out.write("\t};\n");
      out.write("\tch.q = [];\n");
      out.write("\tch.c = function(args) {\n");
      out.write("\t  ch.q.push(args);\n");
      out.write("\t};\n");
      out.write("\tw.ChannelIO = ch;\n");
      out.write("\tfunction l() {\n");
      out.write("\t  if (w.ChannelIOInitialized) {\n");
      out.write("\t    return;\n");
      out.write("\t  }\n");
      out.write("\t  w.ChannelIOInitialized = true;\n");
      out.write("\t  var s = document.createElement('script');\n");
      out.write("\t  s.type = 'text/javascript';\n");
      out.write("\t  s.async = true;\n");
      out.write("\t  s.src = 'https://cdn.channel.io/plugin/ch-plugin-web.js';\n");
      out.write("\t  s.charset = 'UTF-8';\n");
      out.write("\t  var x = document.getElementsByTagName('script')[0];\n");
      out.write("\t  x.parentNode.insertBefore(s, x);\n");
      out.write("\t}\n");
      out.write("\tif (document.readyState === 'complete') {\n");
      out.write("\t  l();\n");
      out.write("\t} else if (window.attachEvent) {\n");
      out.write("\t  window.attachEvent('onload', l);\n");
      out.write("\t} else {\n");
      out.write("\t  window.addEventListener('DOMContentLoaded', l, false);\n");
      out.write("\t  window.addEventListener('load', l, false);\n");
      out.write("\t}\n");
      out.write("\t})();\n");
      out.write("\tChannelIO('boot', {\n");
      out.write("\t\"pluginKey\": \"f8d38dd3-5fce-4786-bd3e-461970ec4f97\"\n");
      out.write("\t\n");
      out.write("})\n");
      out.write("</script>\n");

	session.getAttribute("usrNick");

      out.write("\n");
      out.write("\t<div class=\"wrap\">\n");
      out.write("\t\t<div class=\"intro_bg\">\n");
      out.write("\t\t\t<div class=\"header\">\n");
      out.write("\t\t\t<ul class=\"nav\">\n");
      out.write("\t\t\t\t<div class=\"home\">\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<a href=\"#header\"><img src=\"../resources/images/koravel.png\"></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<input type=\"search\" class=\"searchbar\" placeholder=\"당신이 가고 싶은 여행지는?\">\n");
      out.write("\t\t\t\t\t\t<span>검색</span>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div> <!-- intro End // class=\"wrap\" end-->\n");
      out.write("\t<div>\n");
      out.write("\t   <ul class=\"amount\">\n");
      out.write("                <li>\n");
      out.write("                    <div>\n");
      out.write("                        <a href=\"../region/recommand.do\">\n");
      out.write("                            <div><img src=\"../resources/images/main/sticky-notes.png\"></div>\n");
      out.write("                            <div class=\"contents1\"><b>맞춤추천</b></div>\n");
      out.write("                        \n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <div>\n");
      out.write("                        <a href=\"../festival/festival.do\">\n");
      out.write("                            <div><img src=\"../resources/images/main/festival.png\"></div>\n");
      out.write("                            <div class=\"contents1\"><b>지역행사</b></div>\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <div>\n");
      out.write("                        <a href=\"../board/getBoardMain.do\">\n");
      out.write("                            <div><img src=\"../resources/images/main/community.png\"></div>\n");
      out.write("                            <div class=\"contents1\"><b>커뮤니티</b></div>\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <div>\n");
      out.write("                        <a href=\"../main/tip.do\">\n");
      out.write("                            <div><img src=\"../resources/images/main/light-bulb.png\"></div>\n");
      out.write("                            <div class=\"contents1\"><b>Tip</b></div>\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("\t</div> <!-- amount End -->\n");
      out.write("\t\n");
      out.write("\t<div class=\"main_text0\">\n");
      out.write("            <div class=\"page-wrapper\"> <!-- style=\"position:relative\"; -->\n");
      out.write("                    <!--page slider -->\n");
      out.write("                    <div class=\"post-slider\">\n");
      out.write("                    \t<br>\n");
      out.write("                        <h1 class=\"slider-title\">실시간 Hot 여행지</h1>\n");
      out.write("                        \n");
      out.write("                        <div class=\"post-wrapper\">\n");
      out.write("                            \n");
      out.write("                                <div class=\"post\">\n");
      out.write("                                    <a href=\"#\">\n");
      out.write("                                        <img src=\"../resources/images/main/myeongdong.jpg\" class=\"slider-image\">\n");
      out.write("                                        <div class=\"post-info\">\n");
      out.write("                                            <h2>SEOUL</h2>\n");
      out.write("                                            <p>Asia,Korea[서울]</p>\n");
      out.write("                                        </div>\n");
      out.write("                                    </a>\n");
      out.write("                                </div>\n");
      out.write("                            \n");
      out.write("\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <img src=\"../resources/images/main/jeju1.jpg\" class=\"slider-image\">\n");
      out.write("                                    <div class=\"post-info\">\n");
      out.write("                                        <h2>JEJU</h2>\n");
      out.write("                                        <p>Asia,Korea[제주]</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <img src=\"../resources/images/main/busan1.jpg\" class=\"slider-image\">\n");
      out.write("                                    <div class=\"post-info\">\n");
      out.write("                                        <h2>BUSAN</h2>\n");
      out.write("                                        <p>Asia,Korea[부산]</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <img src=\"../resources/images/main/gangwon.jpg\" class=\"slider-image\">\n");
      out.write("                                    <div class=\"post-info\">\n");
      out.write("                                        <h2>Gangwon-do</h2>\n");
      out.write("                                        <p>Asia,Korea[강원도]</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <img src=\"../resources/images/main/hwaseong.jpg\" class=\"slider-image\">\n");
      out.write("                                    <div class=\"post-info\">\n");
      out.write("                                        <h2>Gyeonggi-do</h2>\n");
      out.write("                                        <p>Asia,Korea[경기도]</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <img src=\"../resources/images/main/boeun.jpg\" class=\"slider-image\">\n");
      out.write("                                    <div class=\"post-info\">\n");
      out.write("                                        <h2>Chungcheong-do</h2>\n");
      out.write("                                        <p>Asia,Korea[충청도]</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <img src=\"../resources/images/main/namhae.jpg\" class=\"slider-image\">\n");
      out.write("                                    <div class=\"post-info\">\n");
      out.write("                                        <h2>Gyeongsang-do</h2>\n");
      out.write("                                        <p>Asia,Korea[경상도]</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </div> \n");
      out.write("\n");
      out.write("                            <div class=\"post\">\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <img src=\"../resources/images/main/jeonju.jpg\" class=\"slider-image\">\n");
      out.write("                                    <div class=\"post-info\">\n");
      out.write("                                        <h2>Jeolla-do</h2>\n");
      out.write("                                        <p>Asia,Korea[전라도]</p>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </div> \n");
      out.write("                            \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div> \n");
      out.write("\t <footer>\n");
      out.write("            <div class=\"footer_wrap\">\n");
      out.write("                <img src=\"../resources/images/koravel.png\" style=\"display: block;\">\n");
      out.write("               \t \t상호명 : Koravel<br>\n");
      out.write("                \t주소 : 서울시 금천구 가산동 426-5 월드메르디앙 2차 413호<br>\n");
      out.write("                \tTEL : 02-AAA-BBBB<br>\n");
      out.write("                \tCopyright© 2021 Koravel, All Right Reserved.<br>\n");
      out.write("                <ul class=\"footer_ul\">\n");
      out.write("                    <li id =\"introduce\">Koravel 소개 |</li>\n");
      out.write("                    <li id=\"agreements\">이용 약관  |</li>\n");
      out.write("                    <li id=\"policy\">개인정보 처리방침</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("     </footer>\n");
      out.write("<script>\n");
      out.write("   const header = document.querySelector(\"#header\");\n");
      out.write("   const backImg = document.querySelector(\".intro_bg\")\n");
      out.write("   const backImgHeight = backImg.getBoundingClientRect().height;\n");
      out.write(" \n");
      out.write("   // 스크롤이 배경이미지 높이를 넘어설 때, 헤더부의 배경이\n");
      out.write("   // 불투명해지게끔 하는 코드.\n");
      out.write("   window.addEventListener(\"scroll\", () => {\n");
      out.write("      if (window.scrollY > backImgHeight) {\n");
      out.write("      \t\theader.setAttribute(\"style\", \"background: blue;\", \"width: 100%;\");\n");
      out.write("   \t  } else {  \n");
      out.write("\t\t\theader.setAttribute(\"style\", \"background: transparent;\");\n");
      out.write("   \t  }\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/weatherApi.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/Main.jsp(110,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty usrNick }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"../usr/usrLogin.do\">로그인</a></li>\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"../usrJoin.do\">회원가입</a></li>\n");
          out.write("\t\t\t\t\t\t\t<li>\n");
          out.write("\t\t\t\t\t\t\t\t<img src=\"../resources/images/currency-exchange.svg\" class=\"currency\">  \n");
          out.write("\t\t\t\t\t\t\t    <span id=\"rate\">국가</span> <!-- 통화명 -->\n");
          out.write("\t\t\t\t\t\t\t    <span id=\"now-rate\">?</span> <!-- 실시간 환율 -->\n");
          out.write("\t\t\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t\t\t<ul id=\"weather\">\n");
          out.write("\t\t\t\t                <li class=\"icon\"><img class=\"icon_weather\" src=\"\" ></li>\n");
          out.write("\t\t\t\t                <li class=\"city\"></li>\n");
          out.write("\t\t\t\t                <li class=\"temp\"></li>\n");
          out.write("           \t\t\t\t\t</ul>\n");
          out.write("\t\t\t            \t<ul id=\"currency\">\n");
          out.write("\t\t\t                \t<li class=\"curr_icon\"></li>\n");
          out.write("\t\t\t                \t<li class=\"cur_unit\"></li>\n");
          out.write("\t\t\t                \t<li class=\"cur_rate\"></li>\n");
          out.write("\t\t\t           \t \t</ul>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/Main.jsp(129,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${! empty usrNick }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"../usr/usrLogout.do\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usrNick.getUsrNick() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 로그아웃하기</a></li>\n");
          out.write("\t\t\t\t\t\t\t<li><a href=\"../myPage/myPage.do\">마이페이지</a></li>\n");
          out.write("\t\t\t\t\t\t\t<li>\n");
          out.write("\t\t\t\t\t\t\t\t<img src=\"../resources/images/currency-exchange.svg\" class=\"currency\">  \n");
          out.write("\t\t\t\t\t\t\t    <span id=\"rate\">국가</span> <!-- 통화명 -->\n");
          out.write("\t\t\t\t\t\t\t    <span id=\"now-rate\">?</span> <!-- 실시간 환율 -->\n");
          out.write("\t\t\t\t\t\t\t</li>\n");
          out.write("\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t<ul id=\"weather\">\n");
          out.write("\t\t\t\t                <li class=\"icon\"><img class=\"icon_weather\" src=\"\" ></li>\n");
          out.write("\t\t\t\t                <li class=\"city\"></li>\n");
          out.write("\t\t\t\t                <li class=\"temp\"></li>\n");
          out.write("           \t\t\t\t\t</ul>\n");
          out.write("\t\t\t            \t<ul id=\"currency\">\n");
          out.write("\t\t\t                \t<li class=\"curr_icon\"></li>\n");
          out.write("\t\t\t                \t<li class=\"cur_unit\"></li>\n");
          out.write("\t\t\t                \t<li class=\"cur_rate\"></li>\n");
          out.write("\t\t\t            \t</ul>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
