/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-01-11 08:13:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tip_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/css/style2.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <title>Tip Page</title>\r\n");
      out.write("    <!-- <script type=\"text/javascript\" src=\"main.js\" defer></script> -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("        <!-- chatbot api -->\r\n");
      out.write("    <!-- Channel Plugin Scripts -->\r\n");
      out.write("<script>\r\n");
      out.write("    (function() {\r\n");
      out.write("    var w = window;\r\n");
      out.write("    if (w.ChannelIO) {\r\n");
      out.write("        return (window.console.error || window.console.log || function(){})('ChannelIO script included twice.');\r\n");
      out.write("    }\r\n");
      out.write("    var ch = function() {\r\n");
      out.write("        ch.c(arguments);\r\n");
      out.write("    };\r\n");
      out.write("    ch.q = [];\r\n");
      out.write("    ch.c = function(args) {\r\n");
      out.write("        ch.q.push(args);\r\n");
      out.write("    };\r\n");
      out.write("    w.ChannelIO = ch;\r\n");
      out.write("    function l() {\r\n");
      out.write("        if (w.ChannelIOInitialized) {\r\n");
      out.write("        return;\r\n");
      out.write("        }\r\n");
      out.write("        w.ChannelIOInitialized = true;\r\n");
      out.write("        var s = document.createElement('script');\r\n");
      out.write("        s.type = 'text/javascript';\r\n");
      out.write("        s.async = true;\r\n");
      out.write("        s.src = 'https://cdn.channel.io/plugin/ch-plugin-web.js';\r\n");
      out.write("        s.charset = 'UTF-8';\r\n");
      out.write("        var x = document.getElementsByTagName('script')[0];\r\n");
      out.write("        x.parentNode.insertBefore(s, x);\r\n");
      out.write("    }\r\n");
      out.write("    if (document.readyState === 'complete') {\r\n");
      out.write("        l();\r\n");
      out.write("    } else if (window.attachEvent) {\r\n");
      out.write("        window.attachEvent('onload', l);\r\n");
      out.write("    } else {\r\n");
      out.write("        window.addEventListener('DOMContentLoaded', l, false);\r\n");
      out.write("        window.addEventListener('load', l, false);\r\n");
      out.write("    }\r\n");
      out.write("    })();\r\n");
      out.write("    ChannelIO('boot', {\r\n");
      out.write("    \"pluginKey\": \"f8d38dd3-5fce-4786-bd3e-461970ec4f97\"\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<!-- End Channel Plugin -->\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("    <!-- <a href=\"https://www.naver.com\"><img class=\"chatbot\"src=\"image/chatbot.png\"></a> -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"header\" id=\"header\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=#header><img src=\"../resources/images/koravel.png\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("            <ul class=\"nav\">\r\n");
      out.write("                <li id=\"weather\">날씨</li>\r\n");
      out.write("                <li id=\"currency\">환율</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"login\">\r\n");
      out.write("                <a href=\"login.jsp\">로그인 </a>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"explain\" id=\"explain\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"explain_wrap\" id =\"explain_wrap\">\r\n");
      out.write("            <h1>INTRODUCTION</h1>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"explain_text0\" id=\"explain_text0\">\r\n");
      out.write("                <h3>\r\n");
      out.write("                    KORAVEL은 여행자를 위한 빅데이터기반 국내 여행 맞춤 정보사이트입니다.<br>\r\n");
      out.write("                    기존 여행 사이트는 한국으로 특화하기에는 정보 분산이 되어 있고,<br>\r\n");
      out.write("                    광고의 범람으로 인해 신뢰성이 저하되어 있고\r\n");
      out.write("                    여행자에게는 고질적인 '선택의 어려움'이 있습니다.<br>\r\n");
      out.write("                    KORAVEL은 기존의 신뢰성 문제를 보완하고,\r\n");
      out.write("                    고객의 취향을 파악한 빅데이터 맞춤 기반 서비스를 통해\r\n");
      out.write("                    한국 여행지 선택에 도움을 줍니다.\r\n");
      out.write("                </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"explain_img\" id=\"explain_img\">\r\n");
      out.write("                <img src=\"../resources/images/tip/form_icon.png\">\r\n");
      out.write("                <h4>회원가입 시 Form을 작성합니다.</h4>\r\n");
      out.write("                <h5>Fill out the form when you sign up.</h5>    \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- <div class=\"explain_arrow\" id=\"explain_arrow\"> -->\r\n");
      out.write("                <img src= \"../resources/images/tip/next_arrow.png\">\r\n");
      out.write("            <!-- </div> -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"explain_img\" id=\"explain_img\">\r\n");
      out.write("                <img src=\"../resources/images/tip/analysis_icon.png\">\r\n");
      out.write("                <h4>입력 정보를 분석합니다.</h4>\r\n");
      out.write("                <h5>We analyze the input information.</h5>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- <div class=\"explain_arrow\" id=\"explain_arrow\"> -->\r\n");
      out.write("                <img src= \"../resources/images/tip/next_arrow.png\">\r\n");
      out.write("            <!-- </div> -->\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"explain_img\" id=\"explain_img\">\r\n");
      out.write("                <img src=\"../resources/images/tip/offer.png\">\r\n");
      out.write("                <h4>맞춤 정보를 제공합니다.</h4>\r\n");
      out.write("                <h5>We provide customized information.</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"tip_wrapper\">\r\n");
      out.write("        <h1>Tips for foreigners</h1><br>\r\n");
      out.write("\r\n");
      out.write("        <h2>Understanding Korean Culture</h2><br><br><br>\r\n");
      out.write("\r\n");
      out.write("        <h4>Korea is not an extremely closed country but there are several unique Korean cultures that only Korea has. There are several situations when traveling Korea in which you don't know what to do. So you may feel uneasy as there aren't people who answer your questions or offer advice on how to act during those situations    \r\n");
      out.write("            Now, shall we take some time to get to know more about Korea?</h3>\r\n");
      out.write("\r\n");
      out.write("        <h2>1. Restaurant Culture in Korea</h2>\r\n");
      out.write("\r\n");
      out.write("        <h3>Q1. How do you order in a restaurant in Korea?</h3>\r\n");
      out.write("        <div class=\"tip_explain\">\r\n");
      out.write("                <img src=\"../resources/images/tip/order.jpg\">\r\n");
      out.write("\r\n");
      out.write("                <h4>When traveling abroad you will start feeling nervous from when you call the waiter/waitress~ Because you are worried that you cannot speak Korean or may not be able to understand what they are trying to say to you.<br><br>\r\n");
      out.write("                    Fortunately, most restaurants especially newly built ones in Korea have a call bell in which you can press and the waiter/waitress will come to you. It may be located in places hard to find like on the side of the table but having the call bell is convenient as there is no need to call the waiter/waitress out loud.\r\n");
      out.write("                </h4>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h3>Q2. The dish came out not cooked yet, what do I do?</h3>\r\n");
      out.write("        <div class=\"tip_explain\">\r\n");
      out.write("                <img src=\"../resources/images/tip/food.jpg\">\r\n");
      out.write("\r\n");
      out.write("                <h4>There are many Korean dishes in which you have to fry, cook, boil it on the spot. In this case there are a lot of cases in which you have to cook the food yourself! If it is a dish you are trying for the first time you will be confused on what to do.<br><br>\r\n");
      out.write("                    This case happens to Koreans a lot as well. I also don't know what to do when going to a restaurant I haven't been to yet. If this happens, ask in basic english how to cook the dish! They will then either cook the dish for you or kindly tell you what to do.\r\n");
      out.write("\r\n");
      out.write("                    When curious of when the dish is ready to eat it would be best to press the call bell and ask the \"Sajangnim\" if it is ready to eat right?\r\n");
      out.write("                </h4>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h3>Q3. Do you have to tip at a Korean restaurant?</h3>\r\n");
      out.write("        <div class=\"tip_explain\">\r\n");
      out.write("                <img src=\"../resources/images/tip/tip.jpg\">\r\n");
      out.write("\r\n");
      out.write("                <h4>You may be curious if you have to tip someone that has provided you with a service such as at a restaurant, hotel or any other service place.\r\n");
      out.write("\r\n");
      out.write("                    To tell you the conclusion first, it is that THERE IS NO NEED TO!<br><br>\r\n");
      out.write("                    In most restaurants in Korea, you pay the bill at the counter and use a lot of credit cards. So there are almost no cases in which you pay the bill at your seat and so no need to tip them or do they expect you to tip them~ The service fee is thought to be included in the bill so the tip culture in Korea does not exist.\r\n");
      out.write("\r\n");
      out.write("                </h4>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h2>2. Korea Transportation Culture</h2>\r\n");
      out.write("\r\n");
      out.write("        <h3>Q1. Korean Transportation is too complicated, I don't know how to reach my final destination! </h3>\r\n");
      out.write("        <div class=\"tip_explain\">\r\n");
      out.write("                <img src=\"../resources/images/tip/transportation.png\">\r\n");
      out.write("\r\n");
      out.write("                <h4>When traveling Korea, you will notice that the public transportation system in Korea is well organized. But because it is complicated it is often that you don't know which subway or bus to ride to reach your final destination.\r\n");
      out.write("\r\n");
      out.write("                    This is the same for Koreans. Thankfully, because people can connect to WiFi and LTE quickly in Korea, it is convenient to search how to reach their destination through their phone.<br><br>\r\n");
      out.write("                    Especially, if you use applications such as Naver Maps, you can know the estimated arrival time and which public transportation you have to use so even locals use this application a lot. If you want to know how to use Naver maps check out this blog linked.\r\n");
      out.write("                </h4>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h3>Q2. The reason why you tap you transportation card</h3>\r\n");
      out.write("        <div class=\"tip_explain\">\r\n");
      out.write("                <img src=\"../resources/images/tip/tab_buscard.jpg\">\r\n");
      out.write("\r\n");
      out.write("                <h4>The reason why you tap you transportation card when getting off is because<br><br>\r\n");
      out.write("\r\n");
      out.write("                    1. You can receive the transit benefit. You can receive a discount on the next mode of public transportation you use when tapping your transportation card when getting off.<br><br>\r\n");
      out.write("                    2. If you don't tap your card when getting off, there is an extra charge! The transportation fee is calculated by how far you have traveled and if you don't tap your card they will assume you went to the farthest place possible and charge you. To use the next mode of public transportation, they add this amount and charge you so don't get surprised. To save the most amount of money you shouldn't forget to tap your card when getting off right?\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </h4>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h2>3. Koreans and Foreigners</h2>\r\n");
      out.write("\r\n");
      out.write("        <h3>Q1. I can't speak a single word of Korean what do I do?</h3>\r\n");
      out.write("        <div class=\"tip_explain\">\r\n");
      out.write("                <img src=\"../resources/images/tip/no_communication.png\">\r\n");
      out.write("\r\n");
      out.write("                <h4>You are bound to run into Koreans when going to restaurants of traveling. But if you can't speak Korean at all or cannot understand a word you are bound to be scared.<br><br>\r\n");
      out.write("                    But as told in the restaurant culture of Korea, most Koreans can speak basic English. Elderly may not speak or be that good in English but they will still try their best to deliver their message to your through gestures. Even if you don't know a single word of Korean don't worry and ask a local!\r\n");
      out.write("                </h4>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h3>Q2. What do Koreans think about Foreigners?\r\n");
      out.write("\r\n");
      out.write("        </h3>\r\n");
      out.write("        <div class=\"tip_explain\">\r\n");
      out.write("                <img src=\"../resources/images/tip/foreigner.jpg\">\r\n");
      out.write("\r\n");
      out.write("                <h4>Recently, there have been an increase of foreigners in Korea but because Korea isn't that open of a country, foreigners may not be familiar with this culture. Also some Koreans may have hostility against foreigners for no reason at all.<br><br>\r\n");
      out.write("                    But this doesn't mean all Koreans hate foreigners and it may be just a way for them to express their fear about something they are not familiar with.<br><br>\r\n");
      out.write("                    You may be scared about being discriminated against for being a foreigner or actually being discriminated. But please know that there are way more Koreans that are nice toward foreigners. Ask for help to people who look nice and are willing to help.\r\n");
      out.write("                </h4>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <h2>Other Koreans Culture</h2>\r\n");
      out.write("\r\n");
      out.write("        <h3>Q1. Koreans drink too much alcohol</h3>\r\n");
      out.write("        <div class=\"tip_explain\">\r\n");
      out.write("                <img src=\"../resources/images/tip/soju2.jpg\">\r\n");
      out.write("\r\n");
      out.write("                <h4>If Koreans are university students or working at a company you may see them drinking excessively.<br><br>\r\n");
      out.write("                    You will be able to see their glasses constantly filled and drinking it all in one go.<br><br>\r\n");
      out.write("                    They also created a hybrid of beer and soju making them get drunk really quick and get full from it.<br><br>\r\n");
      out.write("                    Koreans also experience hardships from this culture.<br><br>\r\n");
      out.write("                    Koreans also try to avoid this if they can. They sometimes throw the alcohol on the ground in secret, or drink half when being told to drink it all in one go, or fill their glass with water or other various methods to not drink as much.\r\n");
      out.write("                </h4>\r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer_wrap\">\r\n");
      out.write("        <div class=\"footer_part1\">\r\n");
      out.write("            <a href=#header><img src=\"../resources/images/tip/koravel.png\"></a><br><br>\r\n");
      out.write("          \t\t\t 상호명 : Koravel<br>\r\n");
      out.write("                \t주소 : 서울시 금천구 가산동 426-5 월드메르디앙 2차 413호<br>\r\n");
      out.write("                \tTEL : 02-AAA-BBBB<br>\r\n");
      out.write("                \tCopyright© 2021 Koravel, All Right Reserved.<br>\r\n");
      out.write("                <ul class=\"footer_ul\">\r\n");
      out.write("                    <li id =\"introduce\">Koravel 소개 |</li>\r\n");
      out.write("                    <li id=\"agreements\">이용 약관  |</li>\r\n");
      out.write("                    <li id=\"policy\">개인정보 처리방침</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer_part1\">\r\n");
      out.write("            <br><br><br><br>\r\n");
      out.write("            문의: kosmo@naver.com<br>\r\n");
      out.write("            FAQ (자주 묻는 질문)<br>\r\n");
      out.write("            운영시간 : 평일 10:00 ~ 18:00(한국시간 기준)<br>\r\n");
      out.write("            찾아오시는 길<br>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const header = document.querySelector(\"#header\");\r\n");
      out.write("    const backImg = document.querySelector(\".intro_bg\")\r\n");
      out.write("    const backImgHeight = backImg.getBoundingClientRect().height;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    // 스크롤이 배경이미지 높이를 넘어설 때, 헤더부의 배경이\r\n");
      out.write("    // 불투명해지게끔 하는 코드.\r\n");
      out.write("window.addEventListener(\"scroll\", () => {\r\n");
      out.write("  if (window.scrollY > backImgHeight) {\r\n");
      out.write("  header.setAttribute(\"style\", \"background:rgba(175, 224, 245, 0.986);\", \"width: 100%;\");\r\n");
      out.write("} else {\r\n");
      out.write("  \r\n");
      out.write("header.setAttribute(\"style\", \"background: transparent;\");\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>   \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
