# Generated by Django 4.0 on 2022-01-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koraveladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'managed': False, 'verbose_name': '게시판 정보', 'verbose_name_plural': '게시판 정보'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'verbose_name': '지역 행사 정보', 'verbose_name_plural': '지역 행사 정보'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False, 'verbose_name': '지역 정보', 'verbose_name_plural': '지역 정보'},
        ),
        migrations.AlterModelOptions(
            name='regionreview',
            options={'managed': False, 'verbose_name': '지역 리뷰 정보', 'verbose_name_plural': '지역 리뷰 정보'},
        ),
        migrations.AlterModelOptions(
            name='usr',
            options={'managed': False, 'verbose_name': '회원 정보', 'verbose_name_plural': '회원 정보'},
        ),
    ]
