/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-01-07 10:00:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.usr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class usrJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>사용자 등록</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- \r\n");
      out.write("          정적자원들은 resources 폴더에 저장\r\n");
      out.write("\t 현재 프로젝트명에서 user 경로를 더한 상태이기에 상위경로를 올라갔다가 resources를 찾음.\r\n");
      out.write(" -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/jquery-1.7.1.js\"></script>\r\n");
      out.write("<script  src=\"../resources/js/js_usrinput.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tdocument.getElementById('Submit').onclick = check;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction check(){\r\n");
      out.write("\t\tif(document.form.usrID.value==\"\"){\r\n");
      out.write("\t\t\talert(\"ID를 확인 해주세요.\")\r\n");
      out.write("\t\t\tdocument.form.usrID.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.form.usrPasswd.value != document.form.usrPasswd2.value){\r\n");
      out.write("\t\t\talert(\"비밀번호를 확인 해주세요.\")\r\n");
      out.write("\t\t\tdocument.form.usrPasswd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.form.usrPasswd.value==\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 확인 해주세요.\")\r\n");
      out.write("\t\t\tdocument.form.usrPasswd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.form.usrEmail.value==\"\"){\r\n");
      out.write("\t\t\talert(\"이메일을 확인 해주세요.\")\r\n");
      out.write("\t\t\tdocument.form.usrPasswd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.form.usrNick.value==\"\"){\r\n");
      out.write("\t\t\talert(\"닉네임을 확인 해주세요.\")\r\n");
      out.write("\t\t\tdocument.form.usrPasswd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.form.usrBirth.value==\"\"){\r\n");
      out.write("\t\t\talert(\"생년월일을 확인 해주세요.\")\r\n");
      out.write("\t\t\tdocument.form.usrPasswd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.form.submit();//전송\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* .normal {  \r\n");
      out.write("font-family: \"굴림\", \"돋움\"; \r\n");
      out.write("font-size: 12; \r\n");
      out.write("font-style: normal; \r\n");
      out.write("font-weight:normal; \r\n");
      out.write("text-decoration: none;\r\n");
      out.write(" } */\r\n");
      out.write("\r\n");
      out.write(".normalbold {  font-family: \"굴림\", \"돋움\"; font-size: 20px;\r\n");
      out.write("font-style: normal; font-weight: bold; text-decoration: none}\r\n");
      out.write("\r\n");
      out.write("/* td{font-weight:bold; }\r\n");
      out.write("a{text-decoration:none} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("table{ width:310px;  margin:auto;  } /* 테이블 가운데 정렬  */\r\n");
      out.write("\r\n");
      out.write(".table1 {  width:390px; border:0px; cellspacing:0px; cellpadding:5px; font-size:16px; }\r\n");
      out.write(".table2 {  width:390px;  cellspacing:0; cellpadding:3px; }\r\n");
      out.write("\r\n");
      out.write(".tb_ttl {background:#ffffff;   }\r\n");
      out.write("\tinput[type=text]{\r\n");
      out.write("\t\tborder: 2px solid #aaa;\r\n");
      out.write(" \t\tmargin:2px 0;\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("/* \t\tpadding:8px;\r\n");
      out.write(" */\t\tbox-size:.3s;\r\n");
      out.write("\t\tfont-size:20px;\r\n");
      out.write("\t\twidth:310px;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=text]:focus{\r\n");
      out.write("\t\tborder-color:dodgerBlue;\r\n");
      out.write("\t\tbox-shadow:0 0 8px 0 dodgerBlue;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=password]{\r\n");
      out.write("\t\tborder: 2px solid #aaa;\r\n");
      out.write(" \t\tmargin:2px 0;\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("/* \t\tpadding:8px;\r\n");
      out.write(" */\t\tbox-size:.3s;\r\n");
      out.write("\t\tfont-size:20px;\r\n");
      out.write("\t\twidth:310px;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=password]:focus{\r\n");
      out.write("\t\tborder-color:dodgerBlue;\r\n");
      out.write("\t\tbox-shadow:0 0 8px 0 dodgerBlue;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=email]{\r\n");
      out.write("\t\tborder: 2px solid #aaa;\r\n");
      out.write(" \t\tmargin:2px 0;\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("/* \t\tpadding:8px;\r\n");
      out.write(" */\t\tbox-size:.3s;\r\n");
      out.write("\t\tfont-size:20px;\r\n");
      out.write("\t\twidth:310px;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=email]:focus{\r\n");
      out.write("\t\tborder-color:dodgerBlue;\r\n");
      out.write("\t\tbox-shadow:0 0 8px 0 dodgerBlue;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=date]{\r\n");
      out.write("\t\tborder: 2px solid #aaa;\r\n");
      out.write(" \t\tmargin:2px 0;\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("/* \t\tpadding:8px;\r\n");
      out.write(" */\t\tbox-size:.3s;\r\n");
      out.write("\t\tfont-size:20px;\r\n");
      out.write("\t\twidth:310px;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=date]:focus{\r\n");
      out.write("\t\tborder-color:dodgerBlue;\r\n");
      out.write("\t\tbox-shadow:0 0 8px 0 dodgerBlue;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#FFFFFF\" style=\"height: 800px;\">\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("    <img alt=\"LogoKoravel\" src=\"../resources/images/koravel.png\" width=\"auto\" height=\"40\"><font size=\"30\"><b> 회 원 가 입</b></font>\r\n");
      out.write("    </div>\r\n");
      out.write(" \t<div align=\"center\"> \r\n");
      out.write("    좋은 여행정보가 가득한 KORAVEL 입니다.<br>\r\n");
      out.write("      아이디, 비밀번호를 찾기위해 <br/>이메일을 정확히 기재해 주세요.\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("<form method=\"post\" action=\"usrInsert.do\" name=\"form\" >\r\n");
      out.write("  <table >\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td class=\"normalbold tb_ttl\"> \r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write(" \t\t\t\t<i class=\"fas fa-portrait fa-fw \" aria-hidden=\"true\"></i>사용자 ID\r\n");
      out.write("        <span id=\"idCheckResult\"   style=\"align:right;font-size:14px;width:150px;color:red\"></span></div>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td class=\"normal\"> \r\n");
      out.write("        <input type=\"text\" name=\"usrID\" id=\"usrID\" size=\"20\"> \r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td class=\"normalbold tb_ttl\">\r\n");
      out.write("        <div ><i class=\"fas fa-lock  fa-fw\" aria-hidden=\"true\"></i>비밀번호</div>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td  class=\"normal\"> \r\n");
      out.write("        <input type=\"password\" name=\"usrPasswd\" id=\"usrPasswd\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td class=\"normalbold tb_ttl\"> \r\n");
      out.write("        <div ><i class=\"fas fa-lock  fa-fw\" aria-hidden=\"true\"></i>비밀번호 확인</div>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td > \r\n");
      out.write("        <input type=\"password\" name=\"usrPasswd2\" id=\"usrPasswd2\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"normalbold tb_ttl\"> \r\n");
      out.write("          <div ><i class=\"fas fa-envelope  fa-fw\" aria-hidden=\"true\"></i>이메일<input type=\"button\" value=\"확인\" name=\"confirm\" id=\"confirm\">\r\n");
      out.write("        <span id=\"emailCheckResult\"   style=\"align:right;font-size:14px;width:150px;color:red\"></span></div>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("\t  <td>\r\n");
      out.write("\t  \t<input type=\"email\" name=\"usrEmail\" id=\"usrEmail\" >\t      \r\n");
      out.write("    </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("<!--     <tr> \r\n");
      out.write("      <td class=\"normalbold tb_ttl\"> \r\n");
      out.write("          <div ><i class=\"fas fa-envelope fa-fw\" aria-hidden=\"true\"></i>이메일 확인</div>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("\t  <td>\r\n");
      out.write("\t  \t<input type=\"email\" name=\"usrEmail2\" id=\"usrEmail2\" >\t      \r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write(" -->      <td class=\"normalbold tb_ttl\"> \r\n");
      out.write("        <div ><i class=\"fas fa-user-tag  fa-fw\" aria-hidden=\"true\"></i>사용자 닉네임</div>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td  class=\"normal\"> \r\n");
      out.write("        <input type=\"text\" name=\"usrNick\" id=\"usrNick\">\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td class=\"normalbold tb_ttl\">\r\n");
      out.write("\t\t<div ><i class=\"fas fa-birthday-cake  fa-fw\" aria-hidden=\"true\"></i>생년월일</div>\r\n");
      out.write("\t  </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("      <td class=\"normal\"> \r\n");
      out.write("\t  \t<input type=\"date\" name=\"usrBirth\" id=\"usrBirth\" >\t      \r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td  class=\"normal\"> \r\n");
      out.write("        <div align=\"center\"> \r\n");
      out.write("          <input type=\"image\" name=\"Submit\" id=\"Submit\"  src=\"../resources/images/login/join.png\" value=\"등   록\" >\r\n");
      out.write("          </div>\r\n");
      out.write("          </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("          <td>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("          <div align=\"center\">\r\n");
      out.write("    \t\t<input type=\"image\" src=\"../resources/images/login/cancel.png\" value=\"취소\"  onclick=\"javascript:history.back()\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("\t<div align=\"center\"><b>\r\n");
      out.write("\t질문에 응해주세요.(선택사항)<br/>\r\n");
      out.write("\t여행지를 선택된 질문을 반영하여 보여드립니다.<br/>\r\n");
      out.write("\t마이페이지에서 재설정 가능합니다. </b>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"chk_info\" value=\"calm\">조용한\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"chk_info\" value=\"active\" checked=\"checked\">활발한\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"chk_info\" value=\"sea\">바다\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"chk_info\" value=\"mt\" checked=\"checked\">산\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"chk_info\" value=\"family\">가족\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"chk_info\" value=\"couple\">데이트\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"chk_info\" value=\"solo\">혼자만의<br/>\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"chk_info\" value=\"experience\">체험\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"chk_info\" value=\"kid\">아이들과\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
