/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2022-01-07 09:59:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.usr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class usrLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t.loginBox{\r\n");
      out.write("\t\tborder: 2px solid #aaa;\r\n");
      out.write("\t\t margin:8px ; \r\n");
      out.write("\t\twidth:290px;\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("\t\tpadding:8px;\r\n");
      out.write("\t\tborder-radius: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=text]{\r\n");
      out.write("\t\twidth:208px;\r\n");
      out.write("\t\tborder: 2px solid #aaa;\r\n");
      out.write("\t\tmargin:8px 0;\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("\t\tpadding:8px;\r\n");
      out.write("\t\tbox-size:.3s;\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=text]:focus{\r\n");
      out.write("\t\tborder-color:dodgerBlue;\r\n");
      out.write("\t\tbox-shadow:0 0 8px 0 dodgerBlue;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=password]{\r\n");
      out.write("\t\twidth:208px;\r\n");
      out.write("\t\tborder: 2px solid #aaa;\r\n");
      out.write("\t\tmargin:8px 0;\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("\t\tpadding:8px;\r\n");
      out.write("\t\tbox-size:.3s;\r\n");
      out.write("\t\tfont-size:25px;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput[type=password]:focus{\r\n");
      out.write("\t\tborder-color:dodgerBlue;\r\n");
      out.write("\t\tbox-shadow:0 0 8px 0 dodgerBlue;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.inputWithIcon{\r\n");
      out.write("\t\tposition:relative;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.inputWithIcon i{\r\n");
      out.write("\t\tpositioin:absolute;\r\n");
      out.write("\t\tleft:0;\r\n");
      out.write("\t\ttop:8px;\r\n");
      out.write("\t\tpadding:9px 8px;\r\n");
      out.write("\t\tcolor:#aaa;\r\n");
      out.write("\t}\r\n");
      out.write(".login_container{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\tdisplay: -webkit-box;\r\n");
      out.write("\tdisplay: -ms-flexbox;\r\n");
      out.write("  \tdisplay: flex;\r\n");
      out.write("  \t-webkit-box-align: center;\r\n");
      out.write("    -ms-flex-align: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("  \t-webkit-box-pack: center;\r\n");
      out.write("    -ms-flex-pack: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tdocument.getElementById('Submit').onclick = check;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction check(){\r\n");
      out.write("\t\tif(document.form.usrID.value==\"\"){\r\n");
      out.write("\t\t\talert(\"ID를 입력하세요.\")\r\n");
      out.write("\t\t\tdocument.form.usrID.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.form.usrPasswd.value==\"\"){\r\n");
      out.write("\t\t\talert(\"패스워드를 입력하세요.\")\r\n");
      out.write("\t\t\tdocument.form.usrPasswd.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.formID.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"login_container\">\r\n");
      out.write("\t<form id=\"formID\" name=\"form\" action=\"login.do\" method=\"post\">\r\n");
      out.write("\t<div id=\"koravel\">\r\n");
      out.write("\t<img alt=\"LogoKoravel\" src=\"../resources/images/koravel.png\" width=\"320px;\" height=\"75\"  >\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"loginBox\" align=\"center\">\r\n");
      out.write(" \t\t\t<div  align=\"center\">\r\n");
      out.write("\t\t\t<img alt=\"login\" src=\"../resources/images/login/login.png\" width=\"auto\" height=\"30\" align=\"center\">\t\r\n");
      out.write(" \t\t    </div>\r\n");
      out.write(" \t\t\t<div class=\"inputWithIcon\" align=\"center\">\r\n");
      out.write(" \t\t\t\t<i class=\"fas fa-portrait fa-2x fa-fw \" aria-hidden=\"true\"></i>\r\n");
      out.write(" \t\t\t\t<input type=\"text\" name=\"usrID\" id=\"usrID\" placeholder=\"아이디\" class=\"loginInput\">\t\t\r\n");
      out.write(" \t\t    </div>\r\n");
      out.write("    \t\t<div class=\"inputWithIcon\" align=\"center\">\r\n");
      out.write("    \t\t\t<i class=\"fas fa-lock fa-2x fa-fw\" aria-hidden=\"true\"></i>\r\n");
      out.write("       \t\t\t<input type=\"password\" name=\"usrPasswd\" id=\"usrPasswd\"placeholder=\"패스워드\" class=\"loginInput\">\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write(" \t\t\t<div  align=\"center\">\r\n");
      out.write("    \t\t<input type=\"image\" name=\"Submit\" id=\"Submit\" src=\"../resources/images/login/loginButton.png\" width=\"auto\" height=\"54\">\r\n");
      out.write("       \t\t</div>\r\n");
      out.write(" \t \r\n");
      out.write(" \t\t\t<div  align=\"center\">\r\n");
      out.write("    \t\t<input type=\"image\"  src=\"../resources/images/login/usrJoin.png\"  value=\"회원가입\" onclick=\"location.href='usrJoin.do'\">\r\n");
      out.write("    \t\t<img alt='bar' src=\"../resources/images/login/bar.png\">\r\n");
      out.write("    \t\t<input type=\"image\" src=\"../resources/images/login/cancel.png\" value=\"취소\" onclick=\"javascript:history.back()\">\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       \t\t<font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font>\r\n");
      out.write("       \t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
